calliBot2.warte(C2SensorWait.distanceCm, C2Check.lessThan, 7)
motors.motorPower(100)
basic.forever(function () {
    basic.showString("McLarry")
    calliBot2.setRgbLed(C2RgbLed.All, 16, 16, 16)
    calliBot2.setLed(C2Motor.beide, C2State.an)
    calliBot2.motor(C2Motor.beide, C2Dir.vorwärts, 100)
    calliBot2.warte(C2SensorWait.distanceCm, C2Check.equal, 18)
    mp3touch.setVolume(100000000)
    music.playTone(698, music.beat(BeatFraction.Double))
    calliBot2.warte(C2SensorWait.distanceCm, C2Check.lessThan, 5)
    MotionKit.driveBackwards(100)
    calliBot2.setRgbLed(C2RgbLed.LH, 16, 0, 0)
    calliBot2.setRgbLed(C2RgbLed.RH, 16, 0, 0)
    MotionKit.turnLeft(90)
    calliBot2.setRgbLed(C2RgbLed.LV, 16, 0, 0)
    calliBot2.setRgbLed(C2RgbLed.LH, 16, 0, 0)
})
